Initial logout commit - error
cedricyong00/proj3-FE pull request #27
Opened 2024-01-25 12:33 UTC by cedricyong00

2024-01-25 13:12 UTC, natsumi-h requested changes
On hold until error resolved

2024-01-25 14:11 UTC, natsumi-h approved these changes

2024-01-25 14:11 UTC, natsumi-h commented on src/components/Layout/Header.jsx
> +    const logoutURL = `${import.meta.env.VITE_API_URL}/logout`;
wrong endpoint url correct: `user/logout`

2024-01-25 14:11 UTC, natsumi-h commented on src/components/Layout/Header.jsx
> +        { email: user.email }
email has to be passed by object as BE API accepts

2024-01-25 14:11 UTC, natsumi-h commented on src/components/Layout/Header.jsx
>  export const Header = ({ user, setUser }) => {
user object passed by props from `Header.jsx` so simply can destruct it and pass to API body

2024-01-25 14:11 UTC, natsumi-h commented
Approved with fix as commented.

@jx0906 
Please approve!

2024-01-26 12:06 UTC, jx0906 approved these changes

2024-01-26 12:07 UTC, merged